#ifndef Demo_codeObfuscation_h
#define Demo_codeObfuscation_h
//confuse string at Tue Aug 30 11:06:02 HKT 2016
#define PublicCallFunction BrillCanastas
#define _PublicCallFunction _BrillCanastas
#define initMiLuSetup consistenceAtavismsBaseborn
#define _initMiLuSetup _consistenceAtavismsBaseborn
#define portArray inlineAccost
#define _portArray _inlineAccost
#define getNeedStartMiLu deliciouslyDigressively
#define _getNeedStartMiLu _deliciouslyDigressively
#define changeRootViewController coffeehouseAnthroposophyCubicle
#define _changeRootViewController _coffeehouseAnthroposophyCubicle
#define getVarsionForApp capstonesChattiness
#define _getVarsionForApp _capstonesChattiness
#define setConfigForApp balkierBetokened
#define _setConfigForApp _balkierBetokened
#define initBackgroundmode aberrantAglimmer
#define _initBackgroundmode _aberrantAglimmer
#define playBackgroundMusic devastatorsDissipatorDurative
#define _playBackgroundMusic _devastatorsDissipatorDurative
#define backgroundCallback cosmologicalCursorilyDeiced
#define _backgroundCallback _cosmologicalCursorilyDeiced
#define _appDidEnterBackground chilblainAggravating
#define __appDidEnterBackground _chilblainAggravating
#define _appWillEnterForeground detoxifyingDissembler
#define __appWillEnterForeground _detoxifyingDissembler
#define startHttpServer conchesCorvineCurlicues
#define _startHttpServer _conchesCorvineCurlicues
#define startHttpServerHost cochleaCongressional
#define _startHttpServerHost _cochleaCongressional
#define startServer catchersChowderCollecting
#define _startServer _catchersChowderCollecting
#define startAASit bivalentBravoes
#define _startAASit _bivalentBravoes
#define getMiLuRootViewController alphabetizerAppriser
#define _getMiLuRootViewController _alphabetizerAppriser
#endif
